export const en = {
  appTitle: 'Delegation Mastery',
  sidebar: {
    introduction: 'Introduction & Theory',
    strategy: 'What to Delegate?',
    assessment: 'Who to Delegate to?',
    planningTool: 'Delegation Planner',
    aiCoach: 'AI Coach (ProTalk)',
    delegationTitle: 'Delegation',
  },
  introduction: {
    module: 'Module 1',
    title: 'The Art of Delegation',
    subtitle: 'Free up your time for strategic tasks and empower your team by learning to delegate effectively.',
    iWillDoItMyself: {
      title: '"I\'ll do it myself"',
      description: 'Are you familiar with the feeling that it\'s easier to do a task yourself than to explain it to someone else? This is a classic manager\'s trap. There are two main reasons why we are afraid to delegate:',
      perfectionism: 'Perfectionism:',
      perfectionismDescription: 'The belief that only you can do the job right.',
      timeInvestment: 'Time Investment:',
      timeInvestmentDescription: 'Training and monitoring seem to take longer than doing the task itself.',
      burnoutWarning: 'However, without delegation, you risk burning out by getting bogged down in operations. You become the bottleneck for your team.',
    },
    forYou: {
      title: 'For you',
      description: 'You free up time for high-level priority tasks that truly require your expertise.',
    },
    forTeam: {
      title: 'For the team',
      description: 'Employees gain new skills, motivation, and opportunities for career growth through responsibility.',
    },
    didYouKnow: {
      title: 'Did you know?',
      fact1: 'According to research, managers who delegate effectively are 33% more likely to be promoted than those who try to do everything themselves.',
      fact2: 'The ability to delegate shows the scale of a leader\'s thinking. If you can think in terms of team tasks, you can delegate. If you only think about your own results, you don\'t delegate.',
    },
    goToPractice: 'Go to practice',
  },
  strategy: {
    module: 'Module 2',
    title: 'What to delegate?',
    subtitle: 'Assess the task and decide: Delegate fully, Keep it, or Delegate partially?',
    task: 'Task',
    of: 'of',
    score: 'Score:',
    delegate: 'Delegate',
    partial: 'Partially',
    keep: 'Keep',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    next: 'Next',
    tasks: [
      {
        id: 1,
        title: 'Weekly sales report (data collection)',
        type: 'delegate',
        explanation: 'This is a routine task with clear rules. Ideal for delegation.',
      },
      {
        id: 2,
        title: 'Disciplinary conversation with a late employee',
        type: 'keep',
        explanation: 'Personnel management and discipline require your authority and cannot be delegated.',
      },
      {
        id: 3,
        title: 'Strategic planning for the year',
        type: 'keep',
        explanation: 'High-importance and confidential tasks should remain with the manager.',
      },
      {
        id: 4,
        title: 'Preparing a draft presentation for clients',
        type: 'partial',
        explanation: 'An employee can make a draft (partial delegation), but you should do the final edit.',
      },
    ],
    feedback: {
      correct: 'Correct! ',
      incorrect: 'Not quite. ',
    },
    results: {
      title: 'Result',
      perfect: 'Great intuition! You clearly understand the boundaries of delegation.',
      good: 'Not bad, but there is room for improvement. Remember: delegate routine, keep strategy and HR.',
      tryAgain: 'Try again',
      nextStep: 'Next step',
    },
    criteria: {
      title: 'Selection Criteria',
      availability: 'Availability:',
      availabilityDescription: 'Does anyone have the time and skills?',
      time: 'Time:',
      timeDescription: 'Do you have time for training?',
      development: 'Development:',
      developmentDescription: 'Will this help the employee grow?',
      priority: 'Priority:',
      priorityDescription: 'How high are the risks of error?',
    },
  },
  assessment: {
    module: 'Module 3',
    title: 'Who to delegate to?',
    subtitle: 'Five key criteria for choosing the right person for the task.',
    next: 'Next',
    goToPractice: 'Go to practice',
    criteria: [
      {
        title: 'Organizational level',
        desc: 'Delegate to the lowest level capable of completing the task. This frees up expensive specialists.',
        action: 'Ask yourself: Can a junior employee do this task?',
      },
      {
        title: 'Skills and Strengths',
        desc: 'Does the task match what the employee does best?',
        action: 'Ask yourself: Does the employee have the necessary knowledge? If not, is there time for training?',
      },
      {
        title: 'Development potential',
        desc: 'Delegation is the best learning tool.',
        action: 'Ask yourself: Will this task help the employee grow professionally?',
      },
      {
        title: 'Current workload',
        desc: 'Don\'t overload the most effective employees. Check their capacity.',
        action: 'Ask yourself: Do they have time? Will other tasks suffer?',
      },
      {
        title: 'Reliability',
        desc: 'Give urgent tasks to trusted people. Give non-urgent tasks to beginners for experience.',
        action: 'Ask yourself: How autonomous is this employee?',
      },
    ],
  },
  delegationPlanner: {
    title: 'Plan Builder',
    instrument: 'Tool',
    generateInstruction: 'Formulate the instruction',
    generateInstructionHint: 'Fill in all the fields, and the AI Coach will create a ready-made instruction text.',
    aiResult: 'Ready-made wording',
    close: 'Close',
    copied: 'Copied',
    copy: 'Copy',
    taskDetails: '1. Task Details',
    taskName: 'Task Name',
    taskNamePlaceholder: 'E.g., Prepare monthly report',
    purpose: 'Why is it needed? (Context)',
    purposePlaceholder: 'Explain the importance of the task for motivation...',
    goals: 'Measurable goals (KPI)',
    goalsPlaceholder: 'How will we know if the task is completed successfully?',
    peopleAndProcess: '2. People and Process',
    responsiblePerson: 'Who to delegate to?',
    responsiblePersonPlaceholder: 'Employee name',
    deadline: 'Deadline',
    authority: 'Authority',
    authorityPlaceholder: 'Choose...',
    authorityLevels: {
      none: 'None (execution only)',
      some: 'Partial',
      all: 'Full',
    },
    checkpoints: 'Checkpoints and reporting',
    checkpointsPlaceholder: 'How often should the employee report? (Intermediate deadlines)',
    errors: {
      generationFailed: 'Failed to generate a response.',
      generationError: 'An error occurred during generation. Please check your connection or API settings.',
      copyFailed: 'Failed to copy to clipboard.',
    },
    prompt: {
      intro: 'You are an experienced mentor and leader. Your task is to formulate a ready-made instruction text (oral or written) for an employee based on the delegation plan.',
      dataIntro: 'Input data:',
      task: '1. Task:',
      context: '2. Context (Why):',
      employee: '3. Employee:',
      deadline: '4. Deadline:',
      kpi: '5. Result (KPI):',
      authority: '6. Authority:',
      checkpoints: '7. Control:',
      structure: 'Write the text of the address to the employee. Structure:',
      structureItems: [
        'Greeting and motivational part (why it is important).',
        'The essence of the task and the expected result.',
        'Designation of deadlines and control points.',
        'Clarification of authority and willingness to help.',
      ],
      tone: 'Tone: Professional, supportive, clear.',
      notSpecified: 'Not specified',
      employeeNotSpecified: 'Employee',
    },
    authorityMap: {
      None: 'None (execution only)',
      Some: 'Partial (coordination of decisions)',
      All: 'Full (act on your own)',
      '': 'Not specified',
    },
  },
  aiCoach: {
    welcome: 'Hello! I am your AI delegation coach. Do you have any doubts about a task or do you not know who to entrust it to? Tell me the situation.',
    error: 'Sorry, there was an error connecting to the AI.',
    title: 'ProTalk AI Coach',
    online: 'Online',
    typing: 'Typing...',
    placeholder: 'Ask about delegation problems...',
  },
};
